"""ajouter_followers

Revision ID: 781c7bf7352d
Revises: 4350ddcff5e3
Create Date: 2024-12-04 16:02:38.480808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781c7bf7352d'
down_revision = '4350ddcff5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
